/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApiPublicActivationQrRouteImport } from './routes/api/public/activation/qr'
import { Route as ApiPublicPesapalIpnRouteImport } from './routes/api/public/pesapal/ipn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivationQrRoute = ApiPublicActivationQrRouteImport.update({
  id: '/api/public/activation/qr',
  path: '/api/public/activation/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPesapalIpnRoute = ApiPublicPesapalIpnRouteImport.update({
  id: '/api/public/pesapal/ipn',
  path: '/api/public/pesapal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/activation/qr': typeof ApiPublicActivationQrRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/activation/qr': typeof ApiPublicActivationQrRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/activation/qr': typeof ApiPublicActivationQrRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/checkout'
    | '/api/public/activation/qr'
    | '/api/public/pesapal/ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/checkout'
    | '/api/public/activation/qr'
    | '/api/public/pesapal/ipn'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/checkout'
    | '/api/public/activation/qr'
    | '/api/public/pesapal/ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiPublicActivationQrRoute: typeof ApiPublicActivationQrRoute
  ApiPublicPesapalIpnRoute: typeof ApiPublicPesapalIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activation/qr': {
      id: '/api/public/activation/qr'
      path: '/api/public/activation/qr'
      fullPath: '/api/public/activation/qr'
      preLoaderRoute: typeof ApiPublicActivationQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pesapal/ipn': {
      id: '/api/public/pesapal/ipn'
      path: '/api/public/pesapal/ipn'
      fullPath: '/api/public/pesapal/ipn'
      preLoaderRoute: typeof ApiPublicPesapalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  CheckoutRoute: CheckoutRoute,
  ApiPublicActivationQrRoute: ApiPublicActivationQrRoute,
  ApiPublicPesapalIpnRoute: ApiPublicPesapalIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
